version: "3.8"
services:
  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: Dio
      MONGO_INITDB_ROOT_PASSWORD: IfT3Kop!2
    ports:
      - "27017:27017"
    networks:
      - mongo-net
networks:
  mongo-net:
    driver: bridge
