spring:
  profiles:
    include: 'prod'
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: "tacocloud"
  data:
    mongodb:
      port: 27017
      host: localhost
      database: tacoclouddb
      username: Dio
      password: IfT3Kop!2
      authentication-database: admin