spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: "tacocloud"
  cassandra:
    keyspace-name: "tacocloud"
    schema-action: recreate
    local-datacenter: datacenter1
    port: 9042