spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: "tacocloud"
  data:
    mongodb:
      port: 27017
      host: localhost
      database: tacoclouddb
      username: Dio
      password: IfT3Kop!2
      authentication-database: admin
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 96a326b6a799970716a3
            client-secret: e57272daf6f47c55b3fd08024b9d0796bc83c2d0
            scope:
              - user