server:
  port: 9000
spring:
  datasource:
    generate-unique-name: false
    name: "AuthDb"
    username: "admin"
    password: "admin"
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
management:
  endpoints:
    web:
      exposure:
        include: '*'