server:
  port: 9000
spring:
  datasource:
    generate-unique-name: false
    name: "AuthDb"
    username: "admin"
    password: "admin"
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.security: trace