logging:
  level:
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
server:
  port: 9090
spring:
  security:
    oauth2:
      client:
        registration:
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: writeIngredients, deleteIngredients, createOrders, deleteOrders, editOrders, createTacos, editTacos, deleteTacos, openid
        provider:
          tacocloud:
            issuer-uri: "http://127.0.0.1:9000"
